### ISSUE TITLE
Animate leaves when attached

### ISSUE THREAD

**Issue by jbobrow** [Move38/ForgetMeNot#6]
Fade down leaves when attached to center (fade up center leaf)

**Comment by jbobrow** [comment]
When a loose piece is attached to a center piece in the Bloom state, the green piece should fade down all but the center face.

**Comment by bigjosh** [comment]
What should the canter show when a game is paused because a petal has been removed?

**Comment by bigjosh** [comment]
What is a better word for the "the dark time between when the user sees the initial state of the puzzle and the changed state of the puzzle"?  Currently called `PAUSE`, but pause is better used for the time when the game is paused due to a petal being removed.

**Comment by jbobrow** [comment]
I believe these were both covered via text message, but here to cover all bases:
The center should do the following:
`setColor(dim(YELLOW, sin8_C(millis()/8)));`

The state for going dark should be called `HIDE`

**Comment by jbobrow** [comment]
The pause with the solid yellow looks great. Leave that as is 👍
